## pandas
---
Basics guide to understand *pandas Python Data Analysis Library*

In [1]:
import numpy as np
import pandas as pd
from numpy import nan as NA
from pandas import DataFrame, Series

In [2]:
np.__version__

'1.17.3'

In [3]:
pd.__version__

'0.25.2'

### Series
---
A Series is a one-dimensional array-like object containing an array of data
(of any NumPy data type) and an associated array of data labels, called its *index*.

In [4]:
obj = Series([4, 7, -5, 3])

In [5]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [6]:
obj.values

array([ 4,  7, -5,  3])

In [7]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [9]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [10]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [11]:
obj2['a']

-5

In [12]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    4
dtype: int64

By default, the index is from $0$ to $len - 1$

In [13]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [14]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [15]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

Integer indexing may generate errors on using -1 as callable index

Another way to think about a Series is as a fixed-length OrderedDict,
as it is a mapping of index values to data values

In [16]:
'b' in obj2

True

In [17]:
'e' in obj2

False

In [18]:
sdata = {
    'Ohio': 35,
    'Texas': 71,
    'Oregon': 16,
    'Utah': 5
}

In [19]:
obj3 = Series(sdata)

In [20]:
obj3

Ohio      35
Texas     71
Oregon    16
Utah       5
dtype: int64

In [21]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [22]:
obj4 = Series(sdata, index=states)

In [23]:
obj4

California     NaN
Ohio          35.0
Oregon        16.0
Texas         71.0
dtype: float64

In [24]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [25]:
obj4.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

Series automatically aligns differently indexed data in arithmetic operations

In [26]:
obj3 + obj4

California      NaN
Ohio           70.0
Oregon         32.0
Texas         142.0
Utah            NaN
dtype: float64

Series object and its index both have *name* attribute

In [27]:
obj4.name = 'population'

In [28]:
obj4.index.name = 'state'

In [29]:
obj4

state
California     NaN
Ohio          35.0
Oregon        16.0
Texas         71.0
Name: population, dtype: float64

In [30]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [31]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame
---
A DataFrame represents a tabular, spreadsheet-like data structure
containing an ordered collection of columns. The DataFrame has both a row and column index.
It can be thought of as a dict of Series.

In [32]:
data = {
    'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
    'year': [2000, 2001, 2002, 2001, 2002],
    'pop': [1.5, 1.7, 3.6, 2.4, 2.9]
}

In [33]:
frame = DataFrame(data)

In [34]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [35]:
frame2 = DataFrame(data,
                   columns=['year', 'state', 'pop', 'debt'],
                   index=['one', 'two', 'three', 'four', 'five'])

In [36]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [37]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [38]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [39]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [40]:
frame2.iloc[0]

year     2000
state    Ohio
pop       1.5
debt      NaN
Name: one, dtype: object

In [41]:
frame2.loc['four']

year       2001
state    Nevada
pop         2.4
debt        NaN
Name: four, dtype: object

In [42]:
frame2['debt'] = 16.5

In [43]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [44]:
frame2['debt'] = np.arange(5)

In [45]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

When assigning lists or arrays to a column, the value’s length must match the length
of the DataFrame. If a Series is assigned, it will be instead conformed exactly to the
DataFrame’s index, inserting missing values in any holes

In [46]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [47]:
frame2['debt'] = val

In [48]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

Assigning a column that doesn’t exist will create a new column. The `del` keyword will
delete columns as with a dict

In [49]:
frame2['eastern'] = frame2.state == 'Ohio'

In [50]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [51]:
del frame2['eastern']

In [52]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

If a nested dict of dicts is passed to a DataFrame,
it will interpret the outer dict keys as the columns
and the inner keys as the row indices

In [53]:
pop = {
    'Nevada': {
        2001: 2.4,
        2002: 2.9
    },
    'Ohio': {
        2000: 1.5,
        2001: 1.7,
        2002: 3.6
    }
}

In [54]:
frame3 = DataFrame(pop)

In [55]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [56]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

dict of Series can also be passed

In [57]:
pdata = {'Ohio': frame3['Ohio'][:-1], 'Nevada': frame3['Nevada'][:2]}

In [58]:
DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [59]:
frame3.index.name = 'year'
frame3.columns.name = 'state'

In [60]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [61]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [62]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

Data inputs to DataFrame constructor:
- 2D ndarray
    - A matrix of data, passing optional row and column labels
- dict of arrays, lists, or tuples
    - Each sequence becomes a column in the DataFrame. All sequences must be the same length
- NumPy structured/record array
    - Treated as the “dict of arrays” case
- dict of Series
    - Each value becomes a column. Indexes from each Series are unioned together to form the result’s row index if no explicit index is passed
- dict of dicts
    - Each inner dict becomes a column. Keys are unioned to form the row index as in the “dict of Series” case
- list of dicts or Series
    - Each item becomes a row in the DataFrame. Union of dict keys or Series indexes become the DataFrame’s column labels
- list of lists or tuples
    - Treated as the “2D ndarray” case
- DataFrame
    - The DataFrame’s indexes are used unless different ones are passed
- NumPy MaskedArray
    - Like the “2D ndarray” case except masked values become NaN/missing in the DataFrame result

### Index objects
---
pandas’s Index objects are responsible for holding the axis labels and other metadata
(like the axis name or names). Any array or other sequence of labels used when
constructing a Series or DataFrame is internally converted to an Index

In [63]:
obj = Series(range(3), index=['a', 'b', 'c'])

In [64]:
obj

a    0
b    1
c    2
dtype: int64

In [65]:
obj.index

Index(['a', 'b', 'c'], dtype='object')

In [66]:
obj.index[1:]

Index(['b', 'c'], dtype='object')

Index objects are immutable so they can be shared safely among data

In [67]:
index = pd.Index(np.arange(3))

In [68]:
obj2 = Series([1.5, -2.5, 0], index=index)

In [69]:
obj2.index is index

True

Index can also behave as a fixed-size set

In [70]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [71]:
'Ohio' in frame3.columns

True

In [72]:
2003 in frame3.index

False

### Reindexing
---

In [73]:
obj = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [74]:
obj

d    4
b    7
a   -5
c    3
dtype: int64

In [75]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [76]:
obj2

a   -5.0
b    7.0
c    3.0
d    4.0
e    NaN
dtype: float64

In [77]:
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0)

a   -5
b    7
c    3
d    4
e    0
dtype: int64

In [78]:
obj3 = Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [79]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [80]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [81]:
obj3.reindex(range(6), method='bfill')

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

<table>
    <caption>reindex methods</caption>
    <tr>
        <th>Argument</th>
        <th>Description</th>
    </tr>
    <tr>
        <td>ffill</td>
        <td>Fill values forward</td>
    </tr>
    <tr>
        <td>bfill</td>
        <td>Fill values backward</td>
    </tr>
</table>

In [82]:
frame = DataFrame(np.arange(9).reshape((3, 3)),
                  index=['a', 'c', 'd'],
                  columns=['Ohio', 'Texas', 'California'])

In [83]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [84]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [85]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [86]:
states = ['Texas', 'Utah', 'California']

In [87]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

### Dropping
---

In [88]:
obj = Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [89]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [90]:
obj.drop(['c', 'd'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [91]:
data = DataFrame(np.arange(16).reshape((4, 4)),
                 index=['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns=['one', 'two', 'three', 'four'])

In [92]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [93]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

### Indexing, selection && filtering

In [94]:
obj = Series(np.arange(4), index=['a', 'b', 'c', 'd'])

In [95]:
obj['b']

1

In [96]:
obj[0]

0

In [97]:
obj[2:4]

c    2
d    3
dtype: int64

In [98]:
obj[['b', 'a', 'd']]

b    1
a    0
d    3
dtype: int64

In [99]:
obj[[1, 3]]

b    1
d    3
dtype: int64

In [100]:
obj[obj < 2]

a    0
b    1
dtype: int64

In slicing with labels, the endpoint is inclusive

In [101]:
obj['b':'c']

b    1
c    2
dtype: int64

In [102]:
obj['b':'c'] = 5

In [103]:
obj

a    0
b    5
c    5
d    3
dtype: int64

In [104]:
data = DataFrame(np.arange(16).reshape((4, 4)),
                 index=['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns=['one', 'two', 'three', 'four'])

In [105]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [106]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [107]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [108]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [109]:
data[2:]

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [110]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [111]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [112]:
data[data < 5] = 0

In [113]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [114]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [115]:
data[['four', 'one']].loc[['Colorado', 'Utah']]

four  one
Colorado     7    0
Utah        11    8

In [116]:
data.iloc[:, [3, 0, 1]].loc[['Colorado', 'Utah']]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [117]:
data.loc[['Colorado', 'Utah']].iloc[:, [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

### Arithmetic and data alignment
---
When adding together objects, if any index pairs are not the same,
the respective index in the result will be the union of the index pairs.

In [118]:
s1 = Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [119]:
s2 = Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [120]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [121]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [122]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

Missing values propagate in arithmetic computations.

In the case of DataFrame, alignment is performed on both the rows and the columns.

In [123]:
df1 = DataFrame(np.arange(9).reshape((3, 3)),
                columns=list('bcd'),
                index=['Ohio', 'Texas', 'Colorado'])

In [124]:
df2 = DataFrame(np.arange(12).reshape((4, 3)),
                columns=list('bde'),
                index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [125]:
df1

b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [126]:
df2

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [127]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [128]:
df1 = DataFrame(np.arange(12).reshape((3, 4)), columns=list('abcd'))
df2 = DataFrame(np.arange(20).reshape((4, 5)), columns=list('abcde'))

In [129]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [130]:
df2

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [131]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [132]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [133]:
df1.reindex(columns=df2.columns, fill_value=0)

a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0

### Operations between DataFrame and Series
---

In NumPy arrays, there is the *broadcasting* property

In [134]:
arr = np.arange(12).reshape((3, 4))

In [135]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [136]:
arr[0]

array([0, 1, 2, 3])

In [137]:
arr - arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

Similarly in pandas DataFrame && Series,

In [138]:
frame = DataFrame(np.arange(12.).reshape((4, 3)),
                  columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [139]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [140]:
series = frame.iloc[0]

In [141]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [142]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

By default, arithmetic broadcasts down the rows.
If an index value is not found in either of DataFrame's column or Series' index,
the objects will be reindexed to form an union

In [143]:
series2 = Series(range(3), index=['b', 'e', 'f'])

In [144]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

**To broadcast over columns instead of rows, we use the arithmetic methods instead of arithmetic operators**

In [145]:
series3 = frame['d']

In [146]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [147]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [148]:
frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### Function application and mapping
---
NumPy ufuncs (element-wise array methods) work fine with pandas objects

In [149]:
frame = DataFrame(np.random.randn(4, 3),
                  columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [150]:
frame

b         d         e
Utah   -0.089083  0.080229 -1.511859
Ohio    0.227243 -0.367620 -1.026711
Texas  -1.107945  0.944741  1.633770
Oregon -0.923297  0.609609 -0.440010

In [151]:
np.abs(frame)

b         d         e
Utah    0.089083  0.080229  1.511859
Ohio    0.227243  0.367620  1.026711
Texas   1.107945  0.944741  1.633770
Oregon  0.923297  0.609609  0.440010

In [152]:
frame.apply(lambda x: x.max() - x.min())

b    1.335188
d    1.312360
e    3.145629
dtype: float64

In [153]:
frame.apply(lambda x: x.max() - x.min(), axis=1)

Utah      1.592088
Ohio      1.253954
Texas     2.741714
Oregon    1.532906
dtype: float64

In [154]:
def f(x: Series) -> Series:
    return Series([x.max(), x.min()], index=['max', 'min'])

In [155]:
frame.apply(f, axis='index')

b         d         e
max  0.227243  0.944741  1.633770
min -1.107945 -0.367620 -1.511859

In [156]:
frame.apply(f, axis='columns')

max       min
Utah    0.080229 -1.511859
Ohio    0.227243 -1.026711
Texas   1.633770 -1.107945
Oregon  0.609609 -0.923297

In [157]:
frame.applymap(lambda x: '{:.2f}'.format(x))

b      d      e
Utah    -0.09   0.08  -1.51
Ohio     0.23  -0.37  -1.03
Texas   -1.11   0.94   1.63
Oregon  -0.92   0.61  -0.44

In [158]:
frame['e'].map(lambda x: '{:.2f}'.format(x))

Utah      -1.51
Ohio      -1.03
Texas      1.63
Oregon    -0.44
Name: e, dtype: object

### Sorting and ranking
---

In [159]:
obj = Series(range(4), index=['d', 'a', 'b', 'c'])

In [160]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [161]:
obj.sort_values()

d    0
a    1
b    2
c    3
dtype: int64

In [162]:
frame = DataFrame(np.arange(8).reshape((2, 4)),
                  index=['three', 'one'],
                  columns=['d', 'a', 'b', 'c'])

In [163]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [164]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [165]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [166]:
frame = DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [167]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [168]:
frame.sort_index()

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [169]:
frame.sort_values(by='a')

b  a
0  4  0
2 -3  0
1  7  1
3  2  1

In [170]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [171]:
obj.rank()

d    1.0
a    2.0
b    3.0
c    4.0
dtype: float64

In [172]:
frame.rank(method='first')

b    a
0  3.0  1.0
1  4.0  3.0
2  1.0  2.0
3  2.0  4.0

### Axis indexes with duplicate values
---

In [173]:
obj = Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [174]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [175]:
obj.index.is_unique

False

In [176]:
obj['a']

a    0
a    1
dtype: int64

In [177]:
obj['c']

4

In [178]:
df = DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [179]:
df

0         1         2
a  0.399373 -1.796396 -1.314578
a  1.194860  0.596614 -0.376609
b -1.163578  0.074973  0.143083
b -1.157216 -0.396874 -0.753838

In [180]:
df.loc['a']

0         1         2
a  0.399373 -1.796396 -1.314578
a  1.194860  0.596614 -0.376609

### Summarizing and Computing Descriptive Statistics
---

In [181]:
df = DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]],
               index=['a', 'b', 'c', 'd'],
               columns=['one', 'two'])

In [182]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

Statistical methods exclude missing data during computation

In [183]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [184]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

NaN values are excluded unless entire slice is NaN.
This can be disabled.

In [185]:
df.mean(axis=1, skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [186]:
df.idxmax()

one    b
two    d
dtype: object

In [187]:
df.idxmin()

one    d
two    b
dtype: object

In [188]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [189]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

describe methods also works on non-numeric data

In [190]:
obj = Series(['a', 'a', 'b', 'c'] * 4)

In [191]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [192]:
frame.head()

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [193]:
frame.tail()

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [194]:
frame.corr()

b         a
b  1.000000  0.549442
a  0.549442  1.000000

In [195]:
frame.cov()

b         a
b  17.666667  1.333333
a   1.333333  0.333333

In [196]:
obj.unique()

array(['a', 'b', 'c'], dtype=object)

In [197]:
obj.value_counts()

a    8
c    4
b    4
dtype: int64

In [198]:
obj.value_counts(sort=True)

a    8
c    4
b    4
dtype: int64

In [199]:
data = DataFrame({
    'Qu1': [1, 3, 4, 3, 4],
    'Qu2': [2, 3, 1, 2, 3],
    'Qu3': [1, 5, 2, 4, 4]
})

In [200]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [201]:
data.apply(pd.value_counts)

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  NaN  2.0  1.0
3  2.0  2.0  NaN
4  2.0  NaN  2.0
5  NaN  NaN  1.0

### Handling Missing Data
---

In [202]:
string_data = Series(['aardvark', 'artichoke', np.nan, 'avocado'])

In [203]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

*Python3's inbuilt None type is also considered NaN by pandas*

In [204]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [205]:
string_data[0] = None

In [206]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [207]:
data = Series([1, NA, 3.5, NA, 7])

In [208]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [209]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [210]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [211]:
data = DataFrame([[1., 6.5, 3.], [1., NA, NA], [NA, NA, NA], [NA, 6.5, 3.]])

In [212]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [213]:
cleaned = data.dropna()

In [214]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [215]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [216]:
data[3] = NA

In [217]:
data

0    1    2   3
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [218]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [219]:
df = DataFrame(np.random.randn(7, 3))

In [220]:
df

0         1         2
0  0.295082  2.382281 -1.401216
1 -2.836092  1.211347 -1.866709
2  0.048956 -0.349723  1.146763
3  1.538612 -1.540971  0.233884
4  2.468202  0.780070  0.750814
5 -0.867926  0.080742 -1.382433
6  1.524430 -0.521577  1.285007

In [221]:
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA

In [222]:
df

0         1         2
0  0.295082       NaN       NaN
1 -2.836092       NaN       NaN
2  0.048956       NaN  1.146763
3  1.538612       NaN  0.233884
4  2.468202  0.780070  0.750814
5 -0.867926  0.080742 -1.382433
6  1.524430 -0.521577  1.285007

In [223]:
df.dropna(thresh=3)

0         1         2
4  2.468202  0.780070  0.750814
5 -0.867926  0.080742 -1.382433
6  1.524430 -0.521577  1.285007

In [224]:
df.fillna(0)

0         1         2
0  0.295082  0.000000  0.000000
1 -2.836092  0.000000  0.000000
2  0.048956  0.000000  1.146763
3  1.538612  0.000000  0.233884
4  2.468202  0.780070  0.750814
5 -0.867926  0.080742 -1.382433
6  1.524430 -0.521577  1.285007

In [225]:
df.fillna({1: 0.5, 2: -1})

0         1         2
0  0.295082  0.500000 -1.000000
1 -2.836092  0.500000 -1.000000
2  0.048956  0.500000  1.146763
3  1.538612  0.500000  0.233884
4  2.468202  0.780070  0.750814
5 -0.867926  0.080742 -1.382433
6  1.524430 -0.521577  1.285007

In [226]:
df.fillna(0, inplace=True)

In [227]:
df

0         1         2
0  0.295082  0.000000  0.000000
1 -2.836092  0.000000  0.000000
2  0.048956  0.000000  1.146763
3  1.538612  0.000000  0.233884
4  2.468202  0.780070  0.750814
5 -0.867926  0.080742 -1.382433
6  1.524430 -0.521577  1.285007

Interpolation can also be used

In [228]:
df = DataFrame(np.random.randn(6, 3))

In [229]:
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA

In [230]:
df

0         1         2
0 -0.311029 -1.103359  0.489758
1 -1.123398  0.021845 -0.556414
2  1.273796       NaN  1.016600
3 -0.985927       NaN -2.027583
4  0.864604       NaN       NaN
5 -0.122965       NaN       NaN

In [231]:
df.fillna(method='ffill')

0         1         2
0 -0.311029 -1.103359  0.489758
1 -1.123398  0.021845 -0.556414
2  1.273796  0.021845  1.016600
3 -0.985927  0.021845 -2.027583
4  0.864604  0.021845 -2.027583
5 -0.122965  0.021845 -2.027583

In [232]:
df.fillna(method='ffill', limit=2)

0         1         2
0 -0.311029 -1.103359  0.489758
1 -1.123398  0.021845 -0.556414
2  1.273796  0.021845  1.016600
3 -0.985927  0.021845 -2.027583
4  0.864604       NaN -2.027583
5 -0.122965       NaN -2.027583

In [233]:
df.fillna(data.mean())

0         1         2
0 -0.311029 -1.103359  0.489758
1 -1.123398  0.021845 -0.556414
2  1.273796  6.500000  1.016600
3 -0.985927  6.500000 -2.027583
4  0.864604  6.500000  3.000000
5 -0.122965  6.500000  3.000000

### Hierarchical indexing
---

In [234]:
data = Series(np.random.randn(10),
              index=[['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'd', 'd'],
                     [1, 2, 3, 1, 2, 3, 1, 2, 2, 3]])

In [235]:
data

a  1    0.714081
   2    0.489721
   3    0.300370
b  1   -1.761408
   2   -1.065337
   3    1.002284
c  1   -0.800646
   2    1.044734
d  2    0.547654
   3   -1.641820
dtype: float64

In [236]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 2),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [237]:
data['b']

1   -1.761408
2   -1.065337
3    1.002284
dtype: float64

In [238]:
data.loc[['b', 'd']]

b  1   -1.761408
   2   -1.065337
   3    1.002284
d  2    0.547654
   3   -1.641820
dtype: float64

In [239]:
data[:, 2]

a    0.489721
b   -1.065337
c    1.044734
d    0.547654
dtype: float64

In [240]:
data.unstack()

1         2         3
a  0.714081  0.489721  0.300370
b -1.761408 -1.065337  1.002284
c -0.800646  1.044734       NaN
d       NaN  0.547654 -1.641820

In [241]:
data.unstack().stack()

a  1    0.714081
   2    0.489721
   3    0.300370
b  1   -1.761408
   2   -1.065337
   3    1.002284
c  1   -0.800646
   2    1.044734
d  2    0.547654
   3   -1.641820
dtype: float64

In [242]:
frame = DataFrame(np.arange(12).reshape((4, 3)),
                  index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns=[['Ohio', 'Ohio', 'Colorado'],
                           ['Green', 'Red', 'Green']])

In [243]:
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [244]:
frame.index.names = ['key1', 'key2']
frame.columns.names = ['state', 'color']

In [245]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [246]:
frame['Ohio', 'Green']

key1  key2
a     1       0
      2       3
b     1       6
      2       9
Name: (Ohio, Green), dtype: int64

In [247]:
frame['Ohio']

color      Green  Red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [248]:
frame['Ohio', 'Green']['a', 1]

0

In [249]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [250]:
frame.swaplevel('key1', 'key2')

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [251]:
frame.sort_index(level=1)

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [252]:
frame.swaplevel(0, 1).sort_index(level=0)

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

In [253]:
frame.sum(level=0, axis=1)

state      Ohio  Colorado
key1 key2                
a    1        1         2
     2        7         5
b    1       13         8
     2       19        11

In [254]:
frame.sum(level=0, axis=0)

state  Ohio     Colorado
color Green Red    Green
key1                    
a         3   5        7
b        15  17       19

In [255]:
frame.sum(level=1, axis=0)

state  Ohio     Colorado
color Green Red    Green
key2                    
1         6   8       10
2        12  14       16

In [256]:
frame = DataFrame({
    'a': range(7),
    'b': range(7, 0, -1),
    'c': ['one', 'one', 'one', 'two', 'two', 'two', 'two'],
    'd': [0, 1, 2, 0, 1, 2, 3]
})

In [257]:
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [258]:
frame2 = frame.set_index(['c', 'd'])

In [259]:
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [260]:
frame.set_index(['c', 'd'], drop=False)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [261]:
frame2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

### Read and Write
---

In [262]:
df = pd.read_csv('ex.csv')

In [263]:
df

Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [264]:
pd.read_table('ex.csv', sep=',')

Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [265]:
pd.read_csv('ex.csv', header=None)

0  1   2   3   4        5
0  NaN  a   b   c   d  message
1  0.0  1   2   3   4    hello
2  1.0  5   6   7   8    world
3  2.0  9  10  11  12      foo

In [266]:
df.to_csv('ex.csv')

### Combining and merging datasets
---

In [267]:
df1 = DataFrame({
    'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
    'data1': range(7)
})

In [268]:
df2 = DataFrame({'key': ['a', 'b', 'd'], 'data2': range(3)})

In [269]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [270]:
df2

key  data2
0   a      0
1   b      1
2   d      2

This is an example of a many-to-one merge situation; the data in df1 has multiple rows
labeled a and b, whereas df2 has only one row for each value in the key column.

In [271]:
pd.merge(df1, df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [272]:
pd.merge(df1, df2, on='key')

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [273]:
df3 = DataFrame({
    'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
    'data1': range(7)
})

In [274]:
df4 = DataFrame({'rkey': ['a', 'b', 'd'], 'data2': range(3)})

In [275]:
df3

lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [276]:
df4

rkey  data2
0    a      0
1    b      1
2    d      2

In [277]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey')

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0

In [278]:
pd.merge(df1, df2, how='outer')

key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

There may also be many-to-many merges

In [279]:
df1 = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'], 'data1': range(6)})

In [280]:
df2 = DataFrame({'key': ['a', 'b', 'a', 'b', 'd'], 'data2': range(5)})

In [281]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [282]:
df2

key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [283]:
pd.merge(df1, df2, on='key', how='left')

key  data1  data2
0    b      0    1.0
1    b      0    3.0
2    b      1    1.0
3    b      1    3.0
4    a      2    0.0
5    a      2    2.0
6    c      3    NaN
7    a      4    0.0
8    a      4    2.0
9    b      5    1.0
10   b      5    3.0

In [284]:
pd.merge(df1, df2, on='key', how='right')

key  data1  data2
0    b    0.0      1
1    b    1.0      1
2    b    5.0      1
3    b    0.0      3
4    b    1.0      3
5    b    5.0      3
6    a    2.0      0
7    a    4.0      0
8    a    2.0      2
9    a    4.0      2
10   d    NaN      4

In [285]:
pd.merge(df1, df2, on='key', how='inner')

key  data1  data2
0   b      0      1
1   b      0      3
2   b      1      1
3   b      1      3
4   b      5      1
5   b      5      3
6   a      2      0
7   a      2      2
8   a      4      0
9   a      4      2

To merge with multiple keys, pass a list of column names

In [286]:
left = DataFrame({
    'key1': ['foo', 'foo', 'bar'],
    'key2': ['one', 'two', 'one'],
    'lval': [1, 2, 3]
})

right = DataFrame({
    'key1': ['foo', 'foo', 'bar', 'bar'],
    'key2': ['one', 'one', 'one', 'two'],
    'rval': [4, 5, 6, 7]
})

In [287]:
left

key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [288]:
right

key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [289]:
pd.merge(left, right, on=['key1', 'key2'], how='inner')

key1 key2  lval  rval
0  foo  one     1     4
1  foo  one     1     5
2  bar  one     3     6

In [290]:
pd.merge(left, right, on=['key1', 'key2'], how='outer')

key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0

When joining columns-on-columns, the indexes on the passed DataFrame objects are discarded.

In [291]:
pd.merge(left, right, on='key1')

key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [292]:
pd.merge(left, right, on='key1', suffixes=('_left', '_right'))

key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

In [293]:
left1 = DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'], 'value': range(6)})
right1 = DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])

In [294]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [295]:
right1

group_val
a        3.5
b        7.0

In some cases, the merge key or keys in a DataFrame will be found in its index.

In [296]:
pd.merge(left1, right1, left_on='key', right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

With hierarchically-indexed data,

In [297]:
lefth = DataFrame({
    'key1': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
    'key2': [2000, 2001, 2002, 2001, 2002],
    'data': np.arange(5.)
})

righth = DataFrame(np.arange(12).reshape((6, 2)),
                   index=[['Nevada', 'Nevada', 'Ohio', 'Ohio', 'Ohio', 'Ohio'],
                          [2001, 2000, 2000, 2000, 2001, 2002]],
                   columns=['event1', 'event2'])

In [298]:
lefth

key1  key2  data
0    Ohio  2000   0.0
1    Ohio  2001   1.0
2    Ohio  2002   2.0
3  Nevada  2001   3.0
4  Nevada  2002   4.0

In [299]:
righth

event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [300]:
pd.merge(lefth, righth, left_on=['key1', 'key2'], right_index=True)

key1  key2  data  event1  event2
0    Ohio  2000   0.0       4       5
0    Ohio  2000   0.0       6       7
1    Ohio  2001   1.0       8       9
2    Ohio  2002   2.0      10      11
3  Nevada  2001   3.0       0       1

In [301]:
pd.merge(lefth,
         righth,
         left_on=['key1', 'key2'],
         right_index=True,
         how='outer')

key1  key2  data  event1  event2
0    Ohio  2000   0.0     4.0     5.0
0    Ohio  2000   0.0     6.0     7.0
1    Ohio  2001   1.0     8.0     9.0
2    Ohio  2002   2.0    10.0    11.0
3  Nevada  2001   3.0     0.0     1.0
4  Nevada  2002   4.0     NaN     NaN
4  Nevada  2000   NaN     2.0     3.0

In [302]:
left2 = DataFrame([[1, 2], [3, 4], [5, 6]],
                  index=['a', 'c', 'e'],
                  columns=['Ohio', 'Nevada'])

right2 = DataFrame([[7, 8], [9, 10], [11, 12], [13, 14]],
                   index=['b', 'c', 'd', 'e'],
                   columns=['Missouri', 'Alabama'])

In [303]:
left2

Ohio  Nevada
a     1       2
c     3       4
e     5       6

In [304]:
right2

Missouri  Alabama
b         7        8
c         9       10
d        11       12
e        13       14

In [305]:
pd.merge(left2, right2, how='outer', left_index=True, right_index=True)

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [306]:
left2.join(right2, how='outer')

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

### Concatenating Along an Axis
---

In [307]:
arr = np.arange(12).reshape((3, 4))

In [308]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [309]:
np.concatenate([arr, arr])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [310]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [311]:
s1 = Series([0, 1], index=['a', 'b'])
s2 = Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = Series([5, 6], index=['f', 'g'])

In [312]:
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [313]:
pd.concat([s1, s2, s3], axis=1, sort=False)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [314]:
s4 = pd.concat([s1 * 5, s3])

In [315]:
s4

a    0
b    5
f    5
g    6
dtype: int64

In [316]:
pd.concat([s1, s4], axis=1, sort=False, join='inner')

0  1
a  0  0
b  1  5

In [317]:
pd.concat([s1, s4], axis=1, sort=False).reindex(index=['a', 'c', 'b', 'e'])

0    1
a  0.0  0.0
c  NaN  NaN
b  1.0  5.0
e  NaN  NaN

In [318]:
result = pd.concat([s1, s1, s3], keys=['one', 'two', 'three'])

In [319]:
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [320]:
result.unstack()

a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  NaN  NaN  5.0  6.0

In [321]:
df1 = DataFrame(np.random.randn(3, 4), columns=['a', 'b', 'c', 'd'])
df2 = DataFrame(np.random.randn(2, 3), columns=['b', 'd', 'a'])

In [322]:
df1

a         b         c         d
0 -0.627706  0.291020 -0.695936  0.819870
1  1.699374 -2.163999 -0.721766  0.506357
2  0.813214  0.352961  0.949394 -0.134448

In [323]:
df2

b         d         a
0  0.263230 -0.307848 -1.498140
1  0.747289 -0.294508  1.577035

In [324]:
pd.concat([df1, df2], ignore_index=True, sort=False)

a         b         c         d
0 -0.627706  0.291020 -0.695936  0.819870
1  1.699374 -2.163999 -0.721766  0.506357
2  0.813214  0.352961  0.949394 -0.134448
3 -1.498140  0.263230       NaN -0.307848
4  1.577035  0.747289       NaN -0.294508

In [325]:
data = DataFrame(np.arange(6).reshape((2, 3)),
                 index=pd.Index(['Ohio', 'Colorado'], name='state'),
                 columns=pd.Index(['one', 'two', 'three'], name='number'))

In [326]:
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [327]:
data.stack()

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [328]:
data.unstack()

number  state   
one     Ohio        0
        Colorado    3
two     Ohio        1
        Colorado    4
three   Ohio        2
        Colorado    5
dtype: int64

### Data Transformation
---

In [329]:
data = DataFrame({
    'k1': ['one'] * 3 + ['two'] * 4,
    'k2': [1, 1, 2, 3, 3, 4, 4]
})

In [330]:
data

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [331]:
data.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [332]:
data.drop_duplicates()

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [333]:
data = DataFrame({
    'food': [
        'bacon', 'pulled pork', 'bacon', 'Pastrami', 'corned beef', 'Bacon',
        'pastrami', 'honey ham', 'nova lox'
    ],
    'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]
})

In [334]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [335]:
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon'
}

In [336]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

### Discretization and Binning
---
Continuous data is often discretized or otherwised separated into “bins” for analysis.

In [337]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]

In [338]:
cats = pd.cut(ages, bins)

In [339]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [340]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

### Detecting and Filtering Outliers
---

In [341]:
data = DataFrame(np.random.randn(1000, 4))

In [342]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.032201    -0.026217    -0.017873    -0.020598
std       0.987693     0.971110     0.975519     1.024737
min      -2.927083    -3.636289    -2.917561    -3.400007
25%      -0.649055    -0.632432    -0.660710    -0.720088
50%      -0.070289    -0.046220    -0.010884    -0.028127
75%       0.633933     0.591477     0.663946     0.685545
max       3.193514     3.092002     3.052347     3.658674

In [343]:
data[np.abs(data) > 3] = np.sign(data) * 3

In [344]:
data

0         1         2         3
0   -0.172804 -1.808572 -0.531497  2.431714
1    1.311739  0.165788  0.303547 -0.437598
2    0.312228 -0.242675 -0.907778  0.166146
3    1.968260  1.506273  0.677548 -0.569534
4    1.928064 -0.168982 -0.271688 -0.050307
..        ...       ...       ...       ...
995 -0.516539 -0.719018  0.764444 -0.261486
996  1.953965 -1.597309 -1.352768  1.092184
997 -1.991591 -0.168087  1.141909 -0.947984
998 -0.216709  1.718333  1.309961  0.512092
999 -1.264136 -0.614582  0.197072 -0.749086

[1000 rows x 4 columns]

### Permutation and Random Sampling
---

In [345]:
df = DataFrame(np.arange(5 * 4).reshape(5, 4))

In [346]:
sampler = np.random.permutation(5)

In [347]:
sampler

array([3, 4, 1, 2, 0])

In [348]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [349]:
df.take(sampler)

0   1   2   3
3  12  13  14  15
4  16  17  18  19
1   4   5   6   7
2   8   9  10  11
0   0   1   2   3

In [350]:
df.take(np.random.permutation(len(df))[:3])

0   1   2   3
2   8   9  10  11
1   4   5   6   7
4  16  17  18  19

In [351]:
bag = np.array([5, 7, -1, 6, 4])
sampler = np.random.randint(0, len(bag), size=10)

In [352]:
sampler

array([3, 4, 3, 4, 1, 3, 2, 1, 0, 1])

In [353]:
draws = bag.take(sampler)

In [354]:
draws

array([ 6,  4,  6,  4,  7,  6, -1,  7,  5,  7])

### Computing Indicator/Dummy Variables
---

In [355]:
df = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'], 'data1': range(6)})

In [356]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [357]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [358]:
df_with_dummy = df[['data1']].join(dummies)

In [359]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

---