## pandas
---
Basics guide to understand *pandas Python Data Analysis Library*

In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series

In [2]:
np.__version__

'1.17.3'

In [3]:
pd.__version__

'0.25.2'

### Series
---
A Series is a one-dimensional array-like object containing an array of data
(of any NumPy data type) and an associated array of data labels, called its *index*.

In [4]:
obj = Series([4, 7, -5, 3])

In [5]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [6]:
obj.values

array([ 4,  7, -5,  3])

In [7]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [9]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [10]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [11]:
obj2['a']

-5

In [12]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    4
dtype: int64

By default, the index is from $0$ to $len - 1$

In [13]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [14]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [15]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

Another way to think about a Series is as a fixed-length OrderedDict,
as it is a mapping of index values to data values.

In [16]:
'b' in obj2

True

In [17]:
'e' in obj2

False

In [18]:
sdata = {
    'Ohio': 35,
    'Texas': 71,
    'Oregon': 16,
    'Utah': 5
}

In [19]:
obj3 = Series(sdata)

In [20]:
obj3

Ohio      35
Texas     71
Oregon    16
Utah       5
dtype: int64

In [21]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [22]:
obj4 = Series(sdata, index=states)

In [23]:
obj4

California     NaN
Ohio          35.0
Oregon        16.0
Texas         71.0
dtype: float64

In [24]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [25]:
obj4.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

Series automatically aligns differently indexed data in arithmetic operations

In [26]:
obj3 + obj4

California      NaN
Ohio           70.0
Oregon         32.0
Texas         142.0
Utah            NaN
dtype: float64

Series object and its index both have *name* attribute

In [27]:
obj4.name = 'population'

In [28]:
obj4.index.name = 'state'

In [29]:
obj4

state
California     NaN
Ohio          35.0
Oregon        16.0
Texas         71.0
Name: population, dtype: float64

In [30]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [31]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame
---
A DataFrame represents a tabular, spreadsheet-like data structure
containing an ordered collection of columns. The DataFrame has both a row and column index.
It can be thought of as a dict of Series.

In [32]:
data = {
    'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
    'year': [2000, 2001, 2002, 2001, 2002],
    'pop': [1.5, 1.7, 3.6, 2.4, 2.9]
}

In [33]:
frame = DataFrame(data)

In [34]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [35]:
frame2 = DataFrame(data,
                   columns=['year', 'state', 'pop', 'debt'],
                   index=['one', 'two', 'three', 'four', 'five'])

In [36]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [37]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [38]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [39]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [40]:
frame2.iloc[0]

year     2000
state    Ohio
pop       1.5
debt      NaN
Name: one, dtype: object

In [41]:
frame2.loc['four']

year       2001
state    Nevada
pop         2.4
debt        NaN
Name: four, dtype: object

In [42]:
frame2['debt'] = 16.5

In [43]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [44]:
frame2['debt'] = np.arange(5)

In [45]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

When assigning lists or arrays to a column, the value’s length must match the length
of the DataFrame. If a Series is assigned, it will be instead conformed exactly to the
DataFrame’s index, inserting missing values in any holes

In [46]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [47]:
frame2['debt'] = val

In [48]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

Assigning a column that doesn’t exist will create a new column. The `del` keyword will
delete columns as with a dict

In [49]:
frame2['eastern'] = frame2.state == 'Ohio'

In [50]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [51]:
del frame2['eastern']

In [52]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

If a nested dict of dicts is passed to a DataFrame,
it will interpret the outer dict keys as the columns
and the inner keys as the row indices

In [53]:
pop = {
    'Nevada': {
        2001: 2.4,
        2002: 2.9
    },
    'Ohio': {
        2000: 1.5,
        2001: 1.7,
        2002: 3.6
    }
}

In [54]:
frame3 = DataFrame(pop)

In [55]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [56]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

dict of Series can also be passed

In [57]:
pdata = {'Ohio': frame3['Ohio'][:-1], 'Nevada': frame3['Nevada'][:2]}

In [58]:
DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [59]:
frame3.index.name = 'year'
frame3.columns.name = 'state'

In [60]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [61]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [62]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

Data inputs to DataFrame constructor:
- 2D ndarray
    - A matrix of data, passing optional row and column labels
- dict of arrays, lists, or tuples
    - Each sequence becomes a column in the DataFrame. All sequences must be the same length
- NumPy structured/record array
    - Treated as the “dict of arrays” case
- dict of Series
    - Each value becomes a column. Indexes from each Series are unioned together to form the result’s row index if no explicit index is passed
- dict of dicts
    - Each inner dict becomes a column. Keys are unioned to form the row index as in the “dict of Series” case
- list of dicts or Series
    - Each item becomes a row in the DataFrame. Union of dict keys or Series indexes become the DataFrame’s column labels
- list of lists or tuples
    - Treated as the “2D ndarray” case
- DataFrame
    - The DataFrame’s indexes are used unless different ones are passed
- NumPy MaskedArray
    - Like the “2D ndarray” case except masked values become NaN/missing in the DataFrame result

### Index objects
---
pandas’s Index objects are responsible for holding the axis labels and other metadata
(like the axis name or names). Any array or other sequence of labels used when
constructing a Series or DataFrame is internally converted to an Index

In [63]:
obj = Series(range(3), index=['a', 'b', 'c'])

In [64]:
obj

a    0
b    1
c    2
dtype: int64

In [65]:
obj.index

Index(['a', 'b', 'c'], dtype='object')

In [66]:
obj.index[1:]

Index(['b', 'c'], dtype='object')

Index objects are immutable so they can be shared safely among data

In [67]:
index = pd.Index(np.arange(3))

In [68]:
obj2 = Series([1.5, -2.5, 0], index=index)

In [69]:
obj2.index is index

True

Index can also behave as a fixed-size set

In [70]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [71]:
'Ohio' in frame3.columns

True

In [72]:
2003 in frame3.index

False

### Reindexing
---

In [73]:
obj = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [74]:
obj

d    4
b    7
a   -5
c    3
dtype: int64

In [75]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [76]:
obj2

a   -5.0
b    7.0
c    3.0
d    4.0
e    NaN
dtype: float64

In [77]:
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0)

a   -5
b    7
c    3
d    4
e    0
dtype: int64

In [78]:
obj3 = Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [79]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [80]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [81]:
obj3.reindex(range(6), method='bfill')

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

<table>
    <caption>reindex methods</caption>
    <tr>
        <th>Argument</th>
        <th>Description</th>
    </tr>
    <tr>
        <td>ffill</td>
        <td>Fill values forward</td>
    </tr>
    <tr>
        <td>bfill</td>
        <td>Fill values backward</td>
    </tr>
</table>

In [82]:
frame = DataFrame(np.arange(9).reshape((3, 3)),
                  index=['a', 'c', 'd'],
                  columns=['Ohio', 'Texas', 'California'])

In [83]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [84]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [85]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [86]:
states = ['Texas', 'Utah', 'California']

In [87]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

### Dropping
---

In [88]:
obj = Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [89]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [90]:
obj.drop(['c', 'd'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [91]:
data = DataFrame(np.arange(16).reshape((4, 4)),
                 index=['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns=['one', 'two', 'three', 'four'])

In [92]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [93]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15